### ISSUE TITLE
Figure plotting

### ISSUE THREAD

**Issue by Martingales** [TheoryDivision/covid19_biosafety_cabinet#1]
Hi Jacob and team,

Love your work and would like to contribute. From your current paper draft I saw that you are currently missing some figures of the data and so I started plotting the data. I would like to push them but am too stupid to figure out how to create a pull request for you all to see. Let me know if you are interested.

Best,
Ruben

**Comment by Martingales** [comment]
So far I created two plots:
Figure 1: Time course of measured radiation
Figure 2: Variance of measured radiation

[Figure_1_UV-C_on-off.pdf](https://github.com/TheoryDivision/covid19_biosafety_cabinet/files/4369354/Figure_1_UV-C_on-off.pdf)
[Figure_2_Variance_UV-C_on-off.pdf](https://github.com/TheoryDivision/covid19_biosafety_cabinet/files/4369355/Figure_2_Variance_UV-C_on-off.pdf)

**Comment by emilydolson** [comment]
Hi Ruben!

Thanks so much for the contribution! Those look great! We're still figuring out what figures to put in the paper, but at a minimum this is really useful to have as a supplement. If you want to try to figure out how to make a pull request with these figures and the code to generate them, I'm happy to help. Alternatively, I can add them myself.

**Comment by Martingales** [comment]
Mh, I tried requesting a pull from different branches (master and a new one figure_plotting) but nothing is displayed in the Pull Request tab.

This was the command I used:
`git request-pull -p master https://github.com/TheoryDivision/covid19_biosafety_cabinet.git`

I think you need to allow me to create pull requests?

**Comment by emilydolson** [comment]
Sorry for not getting back to you sooner, but it looks like you figured it out! Thanks so much for the contribution!
